package com.emoniph.witchery;

import com.emoniph.witchery.Witchery;
import com.emoniph.witchery.blocks.BlockAlluringSkull;
import com.emoniph.witchery.blocks.BlockAltar;
import com.emoniph.witchery.blocks.BlockAreaMarker;
import com.emoniph.witchery.blocks.BlockBarrier;
import com.emoniph.witchery.blocks.BlockBeartrap;
import com.emoniph.witchery.blocks.BlockBloodCrucible;
import com.emoniph.witchery.blocks.BlockBloodRose;
import com.emoniph.witchery.blocks.BlockBloodedWool;
import com.emoniph.witchery.blocks.BlockBramble;
import com.emoniph.witchery.blocks.BlockBrazier;
import com.emoniph.witchery.blocks.BlockCandelabra;
import com.emoniph.witchery.blocks.BlockChalice;
import com.emoniph.witchery.blocks.BlockCircle;
import com.emoniph.witchery.blocks.BlockCircleGlyph;
import com.emoniph.witchery.blocks.BlockCoffin;
import com.emoniph.witchery.blocks.BlockCotton;
import com.emoniph.witchery.blocks.BlockCritterSnare;
import com.emoniph.witchery.blocks.BlockCrystalBall;
import com.emoniph.witchery.blocks.BlockDaylightCollector;
import com.emoniph.witchery.blocks.BlockDemonHeart;
import com.emoniph.witchery.blocks.BlockDisease;
import com.emoniph.witchery.blocks.BlockDistillery;
import com.emoniph.witchery.blocks.BlockDreamCatcher;
import com.emoniph.witchery.blocks.BlockEmberMoss;
import com.emoniph.witchery.blocks.BlockFetish;
import com.emoniph.witchery.blocks.BlockFlowingSpirit;
import com.emoniph.witchery.blocks.BlockForce;
import com.emoniph.witchery.blocks.BlockFumeFunnel;
import com.emoniph.witchery.blocks.BlockGarlicGarland;
import com.emoniph.witchery.blocks.BlockGlintWeed;
import com.emoniph.witchery.blocks.BlockGlowGlobe;
import com.emoniph.witchery.blocks.BlockGrassper;
import com.emoniph.witchery.blocks.BlockInfinityEgg;
import com.emoniph.witchery.blocks.BlockKettle;
import com.emoniph.witchery.blocks.BlockLeapingLily;
import com.emoniph.witchery.blocks.BlockLeechChest;
import com.emoniph.witchery.blocks.BlockLight;
import com.emoniph.witchery.blocks.BlockMirror;
import com.emoniph.witchery.blocks.BlockMirrorWall;
import com.emoniph.witchery.blocks.BlockPerpertualIceStairs;
import com.emoniph.witchery.blocks.BlockPerpetualIce;
import com.emoniph.witchery.blocks.BlockPerpetualIceDoor;
import com.emoniph.witchery.blocks.BlockPerpetualIceFence;
import com.emoniph.witchery.blocks.BlockPerpetualIceGate;
import com.emoniph.witchery.blocks.BlockPerpetualIcePressurePlate;
import com.emoniph.witchery.blocks.BlockPerpetualIceSlab;
import com.emoniph.witchery.blocks.BlockPitDirt;
import com.emoniph.witchery.blocks.BlockPitGrass;
import com.emoniph.witchery.blocks.BlockPlacedItem;
import com.emoniph.witchery.blocks.BlockPlantMine;
import com.emoniph.witchery.blocks.BlockPoppetShelf;
import com.emoniph.witchery.blocks.BlockRefillingChest;
import com.emoniph.witchery.blocks.BlockShadedGlass;
import com.emoniph.witchery.blocks.BlockSilverVat;
import com.emoniph.witchery.blocks.BlockSnowSlab;
import com.emoniph.witchery.blocks.BlockSnowStairs;
import com.emoniph.witchery.blocks.BlockSpanishMoss;
import com.emoniph.witchery.blocks.BlockSpinningWheel;
import com.emoniph.witchery.blocks.BlockSpiritPortal;
import com.emoniph.witchery.blocks.BlockStatueGoddess;
import com.emoniph.witchery.blocks.BlockStatueOfWorship;
import com.emoniph.witchery.blocks.BlockStatueWerewolf;
import com.emoniph.witchery.blocks.BlockStockade;
import com.emoniph.witchery.blocks.BlockTormentPortal;
import com.emoniph.witchery.blocks.BlockVoidBramble;
import com.emoniph.witchery.blocks.BlockWickerBundle;
import com.emoniph.witchery.blocks.BlockWitchCrop;
import com.emoniph.witchery.blocks.BlockWitchDoor;
import com.emoniph.witchery.blocks.BlockWitchLeaves;
import com.emoniph.witchery.blocks.BlockWitchLog;
import com.emoniph.witchery.blocks.BlockWitchSapling;
import com.emoniph.witchery.blocks.BlockWitchWood;
import com.emoniph.witchery.blocks.BlockWitchWoodSlab;
import com.emoniph.witchery.blocks.BlockWitchWoodStairs;
import com.emoniph.witchery.blocks.BlockWitchesOven;
import com.emoniph.witchery.blocks.BlockWolfHead;
import com.emoniph.witchery.brewing.BlockBrew;
import com.emoniph.witchery.brewing.BlockBrewGas;
import com.emoniph.witchery.brewing.BlockBrewLiquidEffect;
import com.emoniph.witchery.brewing.BlockButtonBase;
import com.emoniph.witchery.brewing.BlockCauldron;
import com.emoniph.witchery.brewing.BlockDoorBase;
import com.emoniph.witchery.brewing.BlockLeverBase;
import com.emoniph.witchery.brewing.BlockPressurePlateBase;
import com.emoniph.witchery.brewing.BlockSlurp;
import com.emoniph.witchery.brewing.BlockWitchCactus;
import com.emoniph.witchery.brewing.BlockWitchLilyPad;
import com.emoniph.witchery.brewing.BlockWitchVine;
import com.emoniph.witchery.brewing.BlockWitchWeb;
import com.emoniph.witchery.worldgen.WorldHandlerVillageDistrict;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.block.Block;
import net.minecraft.block.BlockPressurePlate.Sensitivity;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.potion.Potion;
import net.minecraft.potion.PotionEffect;
import net.minecraft.util.IIcon;

public final class WitcheryBlocks {

   public final BlockWitchCrop CROP_BELLADONNA = (BlockWitchCrop)(new BlockWitchCrop(false)).setBlockName("witchery:belladonna").setBlockTextureName("witchery:belladonna");
   public final BlockWitchCrop CROP_MANDRAKE = (BlockWitchCrop)(new BlockWitchCrop(false)).setBlockName("witchery:mandrake").setBlockTextureName("witchery:mandrake");
   public final BlockWitchCrop CROP_ARTICHOKE = (BlockWitchCrop)(new BlockWitchCrop(true)).setBlockName("witchery:artichoke").setBlockTextureName("witchery:artichoke");
   public final BlockWitchCrop CROP_SNOWBELL = (BlockWitchCrop)(new BlockWitchCrop(false)).setBlockName("witchery:snowbell").setBlockTextureName("witchery:snowbell");
   public final BlockWitchCrop CROP_WORMWOOD = (BlockWitchCrop)(new BlockWitchCrop(false)).setBlockName("witchery:wormwood").setBlockTextureName("witchery:wormwood");
   public final BlockWitchCrop CROP_MINDRAKE = (BlockWitchCrop)(new BlockWitchCrop(false, 4, false)).setBlockName("witchery:mindrake").setBlockTextureName("witchery:mindrake");
   public final BlockWitchCrop CROP_WOLFSBANE = (BlockWitchCrop)(new BlockWitchCrop(false, 7, false)).setBlockName("witchery:wolfsbane").setBlockTextureName("witchery:wolfsbane");
   public final BlockWitchCrop CROP_GARLIC = (BlockWitchCrop)(new BlockWitchCrop(false, 5, true)).setBlockName("witchery:garlicplant").setBlockTextureName("witchery:garlic");
   public final Block SAPLING = (new BlockWitchSapling()).setBlockName("witchery:witchsapling").setBlockTextureName("witchery:sapling");
   public final Block LOG = (new BlockWitchLog()).setBlockName("witchery:witchlog").setBlockTextureName("witchery:log");
   public final Block LEAVES = (new BlockWitchLeaves()).setBlockName("witchery:witchleaves").setBlockTextureName("witchery:leaves");
   public final Block VOID_BRAMBLE = (new BlockVoidBramble()).setBlockName("witchery:voidbramble").setBlockTextureName("witchery:voidBramble");
   public final Block BRAMBLE = (new BlockBramble()).setBlockName("witchery:bramble").setBlockTextureName("witchery:bramble");
   public final Block GLINT_WEED = (new BlockGlintWeed()).setBlockName("witchery:glintweed").setBlockTextureName("witchery:glintWeed");
   public final Block SPANISH_MOSS = (new BlockSpanishMoss()).setBlockName("witchery:spanishmoss").setBlockTextureName("witchery:spanishMoss");
   public final Block LEAPING_LILY = (new BlockLeapingLily()).setBlockName("witchery:leapinglily").setBlockTextureName("waterlily");
   public final Block TRAPPED_PLANT = (new BlockPlantMine()).setBlockName("witchery:plantmine").setBlockTextureName("flower_rose");
   public final Block EMBER_MOSS = (new BlockEmberMoss()).setBlockName("witchery:embermoss").setBlockTextureName("witchery:embermoss");
   public final Block CRITTER_SNARE = (new BlockCritterSnare()).setBlockName("witchery:crittersnare").setBlockTextureName("witchery:critterSnare");
   public final Block GRASSPER = (new BlockGrassper()).setBlockName("witchery:grassper").setBlockTextureName("witchery:grassper");
   public final Block BLOOD_ROSE = (new BlockBloodRose()).setBlockName("witchery:bloodrose").setBlockTextureName("witchery:bloodrose");
   public final Block WISPY_COTTON = (new BlockCotton()).setBlockName("witchery:somniancotton").setBlockTextureName("witchery:somnianCotton");
   public final Block WEB = (new BlockWitchWeb()).setBlockName("witchery:web").setBlockTextureName("web");
   public final Block VINE = (new BlockWitchVine()).setBlockName("witchery:vine").setBlockTextureName("vine");
   public final Block CACTUS = (new BlockWitchCactus()).setBlockName("cactus").setBlockTextureName("cactus");
   public final Block LILY = (new BlockWitchLilyPad()).setBlockName("lilypad").setBlockTextureName("waterlily");
   public final Block DEMON_HEART = (new BlockDemonHeart()).setBlockName("witchery:demonheart").setBlockTextureName("witchery:demonHeart");
   public final Block WOLFHEAD = (new BlockWolfHead()).setBlockName("witchery:wolfhead").setBlockTextureName("witchery:wolfhead");
   public final Block PLANKS = (new BlockWitchWood()).setBlockName("witchery:witchwood").setBlockTextureName("witchery:planks");
   public final Block STAIRS_ROWAN;
   public final Block STAIRS_ALDER;
   public final Block STAIRS_HAWTHORN;
   public final Block WOOD_SLAB_SINGLE;
   public final Block WOOD_SLAB_DOUBLE;
   public final Block DOOR_ROWAN;
   public final Block DOOR_ALDER;
   public final Block CHALICE;
   public final Block CANDELABRA;
   public final Block PLACED_ITEMSTACK;
   public final Block ALLURING_SKULL;
   public final Block WICKER_BUNDLE;
   public final Block GLOW_GLOBE;
   public final Block STATUE_GODDESS;
   public final Block STOCKADE;
   public final Block STOCKADE_ICE;
   public final Block PERPETUAL_ICE;
   public final Block PERPETUAL_ICE_DOOR;
   public final Block PERPETUAL_ICE_STAIRS;
   public final Block PERPETUAL_ICE_SLAB_SINGLE;
   public final Block PERPETUAL_ICE_SLAB_DOUBLE;
   public final Block PERPETUAL_ICE_FENCE;
   public final Block PERPETUAL_ICE_FENCE_GATE;
   public final Block PERPETUAL_ICE_PRESSURE_PLATE;
   public final Block SNOW_PRESSURE_PLATE;
   public final Block SNOW_STAIRS;
   public final Block SNOW_SLAB_SINGLE;
   public final Block SNOW_SLAB_DOUBLE;
   public final Block INFINITY_EGG;
   public final BlockSlurp SLURP;
   public final Block PIT_DIRT;
   public final Block PIT_GRASS;
   public final Block GARLIC_GARLAND;
   public final Block BLOODED_WOOL;
   public final Block SHADED_GLASS;
   public final Block SHADED_GLASS_ON;
   public final Block MIRROR_WALL;
   public final Block REFILLING_CHEST;
   public final Block FORCE;
   public final Block TORMENT_STONE;
   public final Block BARRIER;
   public final Block LEECH_CHEST;
   public final Block ALTAR;
   public final BlockKettle KETTLE;
   public final Block POPPET_SHELF;
   public final BlockDreamCatcher DREAM_CATCHER;
   public final Block CRYSTAL_BALL;
   public final BlockSpiritPortal SPIRIT_PORTAL;
   public final Block TORMENT_PORTAL;
   public final Block SPINNING_WHEEL;
   public final Block BRAZIER;
   public final Block OVEN_IDLE;
   public final Block OVEN_BURNING;
   public final Block OVEN_FUMEFUNNEL;
   public final Block OVEN_FUMEFUNNEL_FILTERED;
   public final Block DISTILLERY_IDLE;
   public final Block DISTILLERY_BURNING;
   public final Block FETISH_SCARECROW;
   public final Block FETISH_TREANT_IDOL;
   public final Block FETISH_WITCHS_LADDER;
   public final Block DECURSE_TELEPORT;
   public final Block DECURSE_DIRECTED;
   public final Block STATUE_OF_WORSHIP;
   public final BlockCauldron CAULDRON;
   public final Block WOLF_ALTAR;
   public final Block SILVER_VAT;
   public final Block BEARTRAP;
   public final Block WOLFTRAP;
   public final Block WALLGEN;
   public final BlockCoffin COFFIN;
   public final BlockLight LIGHT;
   public final Block DAYLIGHT_COLLECTOR;
   public final Block BLOOD_CRUCIBLE;
   public final BlockMirror MIRROR;
   public final BlockMirror MIRROR_UNBREAKABLE;
   public final Block CIRCLE;
   public final Block GLYPH_RITUAL;
   public final Block GLYPH_OTHERWHERE;
   public final Block GLYPH_INFERNAL;
   public final Block FLOWING_SPIRIT;
   public final Block HOLLOW_TEARS;
   public final Block DISEASE;
   public final Block BREW;
   public final Block BREW_GAS;
   public final Block BREW_LIQUID;
   public final BlockLeverBase CURSED_LEVER;
   public final BlockDoorBase CURSED_WOODEN_DOOR;
   public final BlockPressurePlateBase CURSED_WOODEN_PRESSURE_PLATE;
   public final BlockPressurePlateBase CURSED_STONE_PRESSURE_PLATE;
   public final BlockPressurePlateBase CURSED_SNOW_PRESSURE_PLATE;
   public final BlockButtonBase CURSED_BUTTON_WOOD;
   public final BlockButtonBase CURSED_BUTTON_STONE;


   public WitcheryBlocks() {
      this.STAIRS_ROWAN = (new BlockWitchWoodStairs(this.PLANKS, 0, 5, 20)).setBlockName("witchery:stairswoodrowan");
      this.STAIRS_ALDER = (new BlockWitchWoodStairs(this.PLANKS, 1, 5, 20)).setBlockName("witchery:stairswoodalder");
      this.STAIRS_HAWTHORN = (new BlockWitchWoodStairs(this.PLANKS, 2, 1, 1)).setBlockName("witchery:stairswoodhawthorn");
      this.WOOD_SLAB_SINGLE = (new BlockWitchWoodSlab(false)).setBlockName("witchery:witchwoodslab");
      this.WOOD_SLAB_DOUBLE = (new BlockWitchWoodSlab(true)).setBlockName("witchery:witchwooddoubleslab");
      this.DOOR_ROWAN = (new BlockWitchDoor()).setBlockName("witchery:rowanwooddoor").setBlockTextureName("witchery:door_rowan").setHardness(5.0F);
      this.DOOR_ALDER = (new BlockWitchDoor()).setBlockName("witchery:alderwooddoor").setBlockTextureName("door_wood").setHardness(3.0F);
      this.CHALICE = (new BlockChalice()).setBlockName("witchery:chalice").setBlockTextureName("witchery:chalice");
      this.CANDELABRA = (new BlockCandelabra()).setBlockName("witchery:candelabra").setBlockTextureName("witchery:candelabra");
      this.PLACED_ITEMSTACK = (new BlockPlacedItem()).setBlockName("witchery:placeditem");
      this.ALLURING_SKULL = (new BlockAlluringSkull()).setBlockName("witchery:alluringskull").setBlockTextureName("witchery:alluringSkull");
      this.WICKER_BUNDLE = (new BlockWickerBundle()).setBlockName("witchery:wickerbundle").setBlockTextureName("witchery:wicker_block");
      this.GLOW_GLOBE = (new BlockGlowGlobe()).setBlockName("witchery:glowglobe").setBlockTextureName("witchery:glowGlobe");
      this.STATUE_GODDESS = (new BlockStatueGoddess()).setBlockName("witchery:statuegoddess").setBlockTextureName("witchery:statueGoddess");
      this.STOCKADE = (new BlockStockade(false)).setBlockName("witchery:stockade").setBlockTextureName("log_oak");
      this.STOCKADE_ICE = (new BlockStockade(true)).setBlockName("witchery:icestockade").setBlockTextureName("ice");
      this.PERPETUAL_ICE = (new BlockPerpetualIce()).setBlockName("witchery:perpetualice").setBlockTextureName("ice");
      this.PERPETUAL_ICE_DOOR = (new BlockPerpetualIceDoor()).setBlockName("witchery:icedoor").setBlockTextureName("witchery:icedoor");
      this.PERPETUAL_ICE_STAIRS = (new BlockPerpertualIceStairs(this.PERPETUAL_ICE, 0)).setBlockName("witchery:icestairs").setBlockTextureName("ice");
      this.PERPETUAL_ICE_SLAB_SINGLE = (new BlockPerpetualIceSlab(false)).setBlockName("witchery:iceslab");
      this.PERPETUAL_ICE_SLAB_DOUBLE = (new BlockPerpetualIceSlab(true)).setBlockName("witchery:icedoubleslab");
      this.PERPETUAL_ICE_FENCE = (new BlockPerpetualIceFence("ice")).setBlockName("witchery:icefence").setBlockTextureName("ice");
      this.PERPETUAL_ICE_FENCE_GATE = (new BlockPerpetualIceGate()).setBlockName("witchery:icefencegate").setBlockTextureName("ice");
      this.PERPETUAL_ICE_PRESSURE_PLATE = (new BlockPerpetualIcePressurePlate(Material.ice)).setBlockName("witchery:icepressureplate").setBlockTextureName("ice");
      this.SNOW_PRESSURE_PLATE = (new BlockPerpetualIcePressurePlate(Material.snow)).setBlockName("witchery:snowpressureplate").setBlockTextureName("snow");
      this.SNOW_STAIRS = (new BlockSnowStairs(Blocks.snow, 0)).setBlockName("witchery:snowstairs").setBlockTextureName("snow");
      this.SNOW_SLAB_SINGLE = (new BlockSnowSlab(false)).setBlockName("witchery:snowslab");
      this.SNOW_SLAB_DOUBLE = (new BlockSnowSlab(true)).setBlockName("witchery:snowdoubleslab");
      this.INFINITY_EGG = (new BlockInfinityEgg()).setBlockName("witchery:infinityegg").setBlockTextureName("witchery:dragon_egg");
      this.SLURP = (BlockSlurp)(new BlockSlurp()).setBlockName("witchery:slurp").setBlockTextureName("witchery:barrier");
      this.PIT_DIRT = (new BlockPitDirt()).setBlockName("witchery:pitdirt").setBlockTextureName("dirt");
      this.PIT_GRASS = (new BlockPitGrass()).setBlockName("witchery:pitgrass").setBlockTextureName("grass");
      this.GARLIC_GARLAND = (new BlockGarlicGarland()).setBlockName("witchery:garlicgarland").setBlockTextureName("witchery:garlicgarlanditem");
      this.BLOODED_WOOL = (new BlockBloodedWool()).setBlockName("witchery:bloodedwool").setBlockTextureName("witchery:bloodedwool");
      this.SHADED_GLASS = (new BlockShadedGlass(false)).setBlockName("witchery:shadedglass").setBlockTextureName("witchery:shadedglassoff");
      this.SHADED_GLASS_ON = (new BlockShadedGlass(true)).setBlockName("witchery:shadedglass_active").setBlockTextureName("witchery:shadedglass");
      this.MIRROR_WALL = (new BlockMirrorWall()).setBlockName("witchery:mirrorwall").setBlockTextureName("witchery:brew");
      this.REFILLING_CHEST = (new BlockRefillingChest()).setBlockName("witchery:refillingchest").setBlockTextureName("textures/entity/chest/normal.png");
      this.FORCE = (new BlockForce(true)).setBlockName("witchery:force").setBlockTextureName("witchery:force");
      this.TORMENT_STONE = (new BlockForce(false)).setBlockName("witchery:tormentstone").setBlockTextureName("mycelium_top");
      this.BARRIER = (new BlockBarrier()).setBlockName("witchery:barrier").setBlockTextureName("witchery:barrier");
      this.LEECH_CHEST = (new BlockLeechChest()).setBlockName("witchery:leechchest").setBlockTextureName("witchery:leechChest");
      this.ALTAR = (new BlockAltar()).setBlockName("witchery:altar").setBlockTextureName("witchery:altar");
      this.KETTLE = (BlockKettle)(new BlockKettle()).setBlockName("witchery:kettle").setBlockTextureName("witchery:kettle");
      this.POPPET_SHELF = (new BlockPoppetShelf()).setBlockName("witchery:poppetshelf").setBlockTextureName("witchery:poppetShelf");
      this.DREAM_CATCHER = (BlockDreamCatcher)(new BlockDreamCatcher()).setBlockName("witchery:dreamcatcher").setBlockTextureName("witchery:dreamCatcher");
      this.CRYSTAL_BALL = (new BlockCrystalBall()).setBlockName("witchery:crystalball").setBlockTextureName("witchery:crystalball");
      this.SPIRIT_PORTAL = (BlockSpiritPortal)(new BlockSpiritPortal(Blocks.snow)).setBlockName("witchery:spiritportal").setBlockTextureName("portal");
      this.TORMENT_PORTAL = (new BlockTormentPortal()).setBlockName("witchery:tormentportal").setBlockTextureName("portal");
      this.SPINNING_WHEEL = (new BlockSpinningWheel()).setBlockName("witchery:spinningwheel").setBlockTextureName("witchery:spinningwheel");
      this.BRAZIER = (new BlockBrazier()).setBlockName("witchery:brazier").setBlockTextureName("witchery:brazier");
      this.OVEN_IDLE = (new BlockWitchesOven(false)).setBlockName("witchery:witchesovenidle").setBlockTextureName("witchery:witchesOven");
      this.OVEN_BURNING = (new BlockWitchesOven(true)).setBlockName("witchery:witchesovenburning").setBlockTextureName("witchery:witchesOven");
      this.OVEN_FUMEFUNNEL = (new BlockFumeFunnel(false)).setBlockName("witchery:fumefunnel").setBlockTextureName("witchery:fumefunnel");
      this.OVEN_FUMEFUNNEL_FILTERED = (new BlockFumeFunnel(true)).setBlockName("witchery:filteredfumefunnel").setBlockTextureName("witchery:fumefunnel");
      this.DISTILLERY_IDLE = (new BlockDistillery(false)).setBlockName("witchery:distilleryidle").setBlockTextureName("witchery:distillery");
      this.DISTILLERY_BURNING = (new BlockDistillery(true)).setBlockName("witchery:distilleryburning").setBlockTextureName("witchery:distillery");
      this.FETISH_SCARECROW = (new BlockFetish()).setBlockName("witchery:scarecrow").setBlockTextureName("witchery:scarecrow");
      this.FETISH_TREANT_IDOL = (new BlockFetish()).setBlockName("witchery:trent").setBlockTextureName("witchery:trent");
      this.FETISH_WITCHS_LADDER = (new BlockFetish()).setBlockName("witchery:witchsladder").setBlockTextureName("witchery:witchsladder");
      this.DECURSE_TELEPORT = (new BlockAreaMarker(BlockAreaMarker.TileEntityAreaTeleportPullProtect.class)).setBlockName("witchery:decurseteleport").setBlockTextureName("witchery:statuemandrake");
      this.DECURSE_DIRECTED = (new BlockAreaMarker(BlockAreaMarker.TileEntityAreaCurseProtect.class)).setBlockName("witchery:decursedirected").setBlockTextureName("witchery:statuewolf");
      this.STATUE_OF_WORSHIP = (new BlockStatueOfWorship()).setBlockName("witchery:statueofworship").setBlockTextureName("stone");
      this.CAULDRON = (BlockCauldron)(new BlockCauldron()).setBlockName("witchery:cauldron").setBlockTextureName("witchery:cauldron");
      this.WOLF_ALTAR = (new BlockStatueWerewolf()).setBlockName("witchery:wolfaltar").setBlockTextureName("stone");
      this.SILVER_VAT = (new BlockSilverVat()).setBlockName("witchery:silvervat").setBlockTextureName("stone");
      this.BEARTRAP = (new BlockBeartrap(false)).setBlockName("witchery:beartrap").setBlockTextureName("iron_block");
      this.WOLFTRAP = (new BlockBeartrap(true)).setBlockName("witchery:wolftrap").setBlockTextureName("iron_block");
      this.WALLGEN = (new WorldHandlerVillageDistrict.Wall.BlockVillageWallGen()).setBlockName("witchery:wallgen").setBlockTextureName("iron_block");
      this.COFFIN = (BlockCoffin)(new BlockCoffin()).setBlockName("witchery:coffinblock").setBlockTextureName("coal_block");
      this.LIGHT = (BlockLight)(new BlockLight()).setBlockName("witchery:light");
      this.DAYLIGHT_COLLECTOR = (new BlockDaylightCollector()).setBlockName("witchery:daylightcollector").setBlockTextureName("witchery:daylightcollector");
      this.BLOOD_CRUCIBLE = (new BlockBloodCrucible()).setBlockName("witchery:bloodcrucible").setBlockTextureName("stone");
      this.MIRROR = (BlockMirror)(new BlockMirror(false)).setBlockName("witchery:mirrorblock").setBlockTextureName("gold_block");
      this.MIRROR_UNBREAKABLE = (BlockMirror)(new BlockMirror(true)).setBlockName("witchery:mirrorblock2").setBlockTextureName("gold_block");
      this.CIRCLE = (new BlockCircle()).setBlockName("witchery:circle").setBlockTextureName("witchery:heartGlyph");
      this.GLYPH_RITUAL = (new BlockCircleGlyph(0, false)).setBlockName("witchery:circleglyphritual").setBlockTextureName("witchery:circleglyph");
      this.GLYPH_OTHERWHERE = (new BlockCircleGlyph(1, false)).setBlockName("witchery:circleglyphotherwhere").setBlockTextureName("witchery:circleglyph");
      this.GLYPH_INFERNAL = (new BlockCircleGlyph(2, false)).setBlockName("witchery:circleglyphinfernal").setBlockTextureName("witchery:circleglyph");
      this.FLOWING_SPIRIT = (new BlockFlowingSpirit(Witchery.Fluids.FLOWING_SPIRIT, new PotionEffect(Potion.regeneration.id, 100, 1), new PotionEffect(Potion.weakness.id, 300, 1), true, true)).setBlockName("witchery:spiritflowing").setBlockTextureName("witchery:flowspirit");
      this.HOLLOW_TEARS = (new BlockFlowingSpirit(Witchery.Fluids.HOLLOW_TEARS, new PotionEffect(Potion.weakness.id, 100, 1), new PotionEffect(Potion.regeneration.id, 100, 1), false, false)).setBlockName("witchery:hollowtears").setBlockTextureName("witchery:tears");
      this.DISEASE = (new BlockDisease(Witchery.Fluids.DISEASE)).setBlockName("witchery:disease").setBlockTextureName("witchery:disease");
      this.BREW = (new BlockBrew(Witchery.Fluids.BREW)).setBlockName("witchery:brew").setBlockTextureName("witchery:brew");
      this.BREW_GAS = (new BlockBrewGas()).setBlockName("witchery:brewgas").setBlockTextureName("witchery:brewgas");
      this.BREW_LIQUID = (new BlockBrewLiquidEffect()).setBlockName("witchery:brewliquid").setBlockTextureName("witchery:brew");
      this.CURSED_LEVER = (BlockLeverBase)(new BlockLeverBase()).setBlockName("witchery:clever");
      this.CURSED_WOODEN_DOOR = (BlockDoorBase)(new BlockDoorBase(Material.wood)).setBlockName("witchery:cwoodendoor").setBlockTextureName("door_wood");
      this.CURSED_WOODEN_PRESSURE_PLATE = (BlockPressurePlateBase)(new BlockPressurePlateBase(Blocks.wooden_pressure_plate, "planks_oak", Sensitivity.everything)).setBlockName("witchery:cwoodpressureplate");
      this.CURSED_STONE_PRESSURE_PLATE = (BlockPressurePlateBase)(new BlockPressurePlateBase(Blocks.stone_pressure_plate, "stone", Sensitivity.mobs)).setBlockName("witchery:cstonepressureplate");
      this.CURSED_SNOW_PRESSURE_PLATE = (BlockPressurePlateBase)(new BlockPressurePlateBase(this.SNOW_PRESSURE_PLATE, "snow", Sensitivity.everything)).setBlockName("witchery:csnowpressureplate");
      this.CURSED_BUTTON_WOOD = (BlockButtonBase)(new BlockButtonBase(true) {
         @SideOnly(Side.CLIENT)
         public IIcon getIcon(int p_149691_1_, int p_149691_) {
            return Blocks.planks.getBlockTextureFromSide(1);
         }
      }).setBlockName("witchery:cbuttonwood");
      this.CURSED_BUTTON_STONE = (BlockButtonBase)(new BlockButtonBase(false) {
         @SideOnly(Side.CLIENT)
         public IIcon getIcon(int p_149691_1_, int p_149691_2_) {
            return Blocks.stone.getBlockTextureFromSide(1);
         }
      }).setBlockName("witchery:cbuttonstone");
   }
}
