package com.emoniph.witchery.client.model;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

@SideOnly(Side.CLIENT)
public class ModelWolfAltar extends ModelBase {

   public ModelRenderer shape1;
   public ModelRenderer shape1_1;
   public ModelRenderer shape1_2;
   public ModelRenderer bipedBody;
   public ModelRenderer wolfBody;
   public ModelRenderer wolfBody_1;
   public ModelRenderer shape37;
   public ModelRenderer bipedLeftLeg;
   public ModelRenderer bipedLeftArm;
   public ModelRenderer bipedRightLeg;
   public ModelRenderer bipedRightArm;
   public ModelRenderer wolfHeadMain0;
   public ModelRenderer bipedRightLegLower;
   public ModelRenderer shaft;
   public ModelRenderer wolfHeadMain3;
   public ModelRenderer wolfHeadMain1;
   public ModelRenderer wolfHeadMain2;
   public ModelRenderer wolfMane;
   public ModelRenderer wolfHeadMain0_1;
   public ModelRenderer wolfTail;
   public ModelRenderer wolfLeg2;
   public ModelRenderer wolfLeg1;
   public ModelRenderer wolfLeg4;
   public ModelRenderer wolfLeg3;
   public ModelRenderer wolfHeadMain3_1;
   public ModelRenderer wolfHeadMain2_1;
   public ModelRenderer wolfHeadMain1_1;
   public ModelRenderer wolfMane_1;
   public ModelRenderer wolfHeadMain0_2;
   public ModelRenderer wolfTail_1;
   public ModelRenderer wolfLeg2_1;
   public ModelRenderer wolfLeg1_1;
   public ModelRenderer wolfLeg4_1;
   public ModelRenderer wolfLeg3_1;
   public ModelRenderer wolfHeadMain3_2;
   public ModelRenderer wolfHeadMain2_2;
   public ModelRenderer wolfHeadMain1_2;


   public ModelWolfAltar() {
      super.textureWidth = 128;
      super.textureHeight = 128;
      this.wolfHeadMain1_2 = new ModelRenderer(this, 16, 14);
      this.wolfHeadMain1_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain1_2.addBox(-3.0F, -4.5F, -10.0F, 2, 2, 1);
      this.bipedBody = new ModelRenderer(this, 16, 16);
      this.bipedBody.setRotationPoint(0.0F, 3.1F, 0.0F);
      this.bipedBody.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4);
      this.wolfHeadMain2_2 = new ModelRenderer(this, 16, 14);
      this.wolfHeadMain2_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain2_2.addBox(1.0F, -4.5F, -10.0F, 2, 2, 1);
      this.bipedRightLeg = new ModelRenderer(this, 0, 16);
      this.bipedRightLeg.mirror = true;
      this.bipedRightLeg.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.bipedRightLeg.addBox(-4.0F, 7.4F, 8.0F, 4, 6, 4);
      this.setRotateAngle(this.bipedRightLeg, -1.0471976F, 0.0F, 0.0F);
      this.wolfMane = new ModelRenderer(this, 21, 0);
      this.wolfMane.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfMane.addBox(-4.0F, -3.0F, -9.0F, 8, 7, 6);
      this.setRotateAngle(this.wolfMane, 0.0F, -0.13665928F, 0.0F);
      this.wolfMane_1 = new ModelRenderer(this, 21, 0);
      this.wolfMane_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfMane_1.addBox(-4.0F, -3.0F, -9.0F, 8, 7, 6);
      this.bipedRightLegLower = new ModelRenderer(this, 18, 0);
      this.bipedRightLegLower.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.bipedRightLegLower.addBox(-4.0F, 15.7F, -6.2F, 4, 6, 4);
      this.setRotateAngle(this.bipedRightLegLower, 0.95609134F, 0.0F, 0.0F);
      this.wolfHeadMain3 = new ModelRenderer(this, 0, 10);
      this.wolfHeadMain3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain3.addBox(-1.5F, -3.1F, -5.0F, 3, 3, 4);
      this.shape37 = new ModelRenderer(this, 0, 0);
      this.shape37.setRotationPoint(-3.9F, 18.0F, -6.5F);
      this.shape37.addBox(0.0F, 0.0F, 0.0F, 4, 2, 4);
      this.wolfLeg3 = new ModelRenderer(this, 0, 18);
      this.wolfLeg3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfLeg3.addBox(-2.5F, 4.0F, -8.0F, 2, 8, 2);
      this.setRotateAngle(this.wolfLeg3, 0.0F, -0.091106184F, 0.0F);
      this.bipedRightArm = new ModelRenderer(this, 40, 16);
      this.bipedRightArm.mirror = true;
      this.bipedRightArm.setRotationPoint(0.0F, 2.0F, 0.0F);
      this.bipedRightArm.addBox(-8.0F, -2.0F, -2.0F, 4, 12, 4);
      this.setRotateAngle(this.bipedRightArm, -2.4586453F, 0.4098033F, 0.0F);
      this.shape1_2 = new ModelRenderer(this, 0, 0);
      this.shape1_2.setRotationPoint(-8.0F, 20.0F, -8.0F);
      this.shape1_2.addBox(0.0F, 0.0F, 0.0F, 16, 1, 16);
      this.wolfLeg2_1 = new ModelRenderer(this, 0, 18);
      this.wolfLeg2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfLeg2_1.addBox(0.5F, 4.0F, 3.0F, 2, 8, 2);
      this.wolfHeadMain1_1 = new ModelRenderer(this, 16, 14);
      this.wolfHeadMain1_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain1_1.addBox(-3.0F, -4.5F, -10.0F, 2, 2, 1);
      this.wolfLeg4 = new ModelRenderer(this, 0, 18);
      this.wolfLeg4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfLeg4.addBox(0.5F, 4.0F, -8.0F, 2, 8, 2);
      this.setRotateAngle(this.wolfLeg4, 0.0F, -0.091106184F, 0.0F);
      this.shaft = new ModelRenderer(this, 0, 33);
      this.shaft.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.shaft.addBox(-6.5F, 8.0F, -17.9F, 1, 1, 40);
      this.wolfHeadMain0_2 = new ModelRenderer(this, 0, 0);
      this.wolfHeadMain0_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain0_2.addBox(-3.0F, -2.5F, -13.0F, 6, 6, 4);
      this.bipedLeftLeg = new ModelRenderer(this, 0, 16);
      this.bipedLeftLeg.mirror = true;
      this.bipedLeftLeg.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.bipedLeftLeg.addBox(0.0F, 12.0F, -2.0F, 4, 12, 4);
      this.shape1 = new ModelRenderer(this, 0, 0);
      this.shape1.setRotationPoint(-8.0F, 22.0F, -8.0F);
      this.shape1.addBox(0.0F, 0.0F, 0.0F, 16, 2, 16);
      this.bipedLeftArm = new ModelRenderer(this, 40, 16);
      this.bipedLeftArm.mirror = true;
      this.bipedLeftArm.setRotationPoint(0.0F, 2.0F, 0.0F);
      this.bipedLeftArm.addBox(4.0F, -2.0F, -2.0F, 4, 12, 4);
      this.setRotateAngle(this.bipedLeftArm, -0.4553564F, -0.13665928F, 0.0F);
      this.wolfLeg4_1 = new ModelRenderer(this, 0, 18);
      this.wolfLeg4_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfLeg4_1.addBox(0.5F, 4.0F, -8.0F, 2, 8, 2);
      this.wolfHeadMain2_1 = new ModelRenderer(this, 16, 14);
      this.wolfHeadMain2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain2_1.addBox(1.0F, -4.5F, -10.0F, 2, 2, 1);
      this.wolfHeadMain3_2 = new ModelRenderer(this, 0, 10);
      this.wolfHeadMain3_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain3_2.addBox(-1.5F, 0.5F, -17.1F, 3, 3, 4);
      this.wolfLeg1_1 = new ModelRenderer(this, 0, 18);
      this.wolfLeg1_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfLeg1_1.addBox(-2.5F, 4.0F, 3.0F, 2, 8, 2);
      this.wolfLeg3_1 = new ModelRenderer(this, 0, 18);
      this.wolfLeg3_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfLeg3_1.addBox(-2.5F, 4.0F, -8.0F, 2, 8, 2);
      this.wolfBody = new ModelRenderer(this, 18, 14);
      this.wolfBody.setRotationPoint(-5.0F, 14.0F, 3.5F);
      this.wolfBody.addBox(-3.0F, -2.0F, -3.0F, 6, 6, 9);
      this.setRotateAngle(this.wolfBody, 0.0F, 0.27314404F, 0.0F);
      this.wolfLeg2 = new ModelRenderer(this, 0, 18);
      this.wolfLeg2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfLeg2.addBox(0.5F, 4.0F, 3.0F, 2, 8, 2);
      this.shape1_1 = new ModelRenderer(this, 0, 0);
      this.shape1_1.setRotationPoint(-7.0F, 21.0F, -7.0F);
      this.shape1_1.addBox(0.0F, 0.0F, 0.0F, 14, 1, 14);
      this.wolfTail = new ModelRenderer(this, 9, 18);
      this.wolfTail.setRotationPoint(0.0F, 0.6F, 0.0F);
      this.wolfTail.addBox(-1.0F, 0.0F, 4.0F, 2, 8, 2);
      this.setRotateAngle(this.wolfTail, 0.31869712F, 0.0F, 0.0F);
      this.wolfHeadMain3_1 = new ModelRenderer(this, 0, 10);
      this.wolfHeadMain3_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain3_1.addBox(-1.5F, 0.5F, -17.1F, 3, 3, 4);
      this.wolfTail_1 = new ModelRenderer(this, 9, 18);
      this.wolfTail_1.setRotationPoint(0.0F, 0.6F, 0.0F);
      this.wolfTail_1.addBox(-1.0F, 0.0F, 4.0F, 2, 8, 2);
      this.setRotateAngle(this.wolfTail_1, 0.31869712F, 0.0F, 0.0F);
      this.wolfLeg1 = new ModelRenderer(this, 0, 18);
      this.wolfLeg1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfLeg1.addBox(-2.5F, 4.0F, 3.0F, 2, 8, 2);
      this.wolfHeadMain1 = new ModelRenderer(this, 16, 14);
      this.wolfHeadMain1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain1.addBox(-3.0F, -8.0F, 2.0F, 2, 2, 1);
      this.wolfBody_1 = new ModelRenderer(this, 18, 14);
      this.wolfBody_1.setRotationPoint(5.5F, 14.0F, -2.0F);
      this.wolfBody_1.addBox(-3.0F, -2.0F, -3.0F, 6, 6, 9);
      this.setRotateAngle(this.wolfBody_1, 0.0F, 0.31869712F, 0.0F);
      this.wolfHeadMain2 = new ModelRenderer(this, 16, 14);
      this.wolfHeadMain2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain2.addBox(1.0F, -8.0F, 2.0F, 2, 2, 1);
      this.wolfHeadMain0 = new ModelRenderer(this, 0, 42);
      this.wolfHeadMain0.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain0.addBox(-3.0F, -6.0F, -2.0F, 6, 6, 5);
      this.setRotateAngle(this.wolfHeadMain0, 0.13665928F, 0.13665928F, 0.0F);
      this.wolfHeadMain0_1 = new ModelRenderer(this, 0, 0);
      this.wolfHeadMain0_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.wolfHeadMain0_1.addBox(-3.0F, -2.5F, -13.0F, 6, 6, 4);
      this.setRotateAngle(this.wolfHeadMain0_1, -0.22759093F, -0.22759093F, 0.0F);
      this.bipedBody.addChild(this.bipedLeftLeg);
      this.wolfHeadMain0_1.addChild(this.wolfHeadMain1_1);
      this.bipedRightLeg.addChild(this.bipedRightLegLower);
      this.wolfHeadMain0.addChild(this.wolfHeadMain3);
      this.wolfBody.addChild(this.wolfHeadMain0_1);
      this.bipedBody.addChild(this.wolfHeadMain0);
      this.wolfHeadMain0.addChild(this.wolfHeadMain2);
      this.wolfHeadMain0.addChild(this.wolfHeadMain1);
      this.wolfBody.addChild(this.wolfLeg1);
      this.wolfBody_1.addChild(this.wolfTail_1);
      this.wolfHeadMain0_1.addChild(this.wolfHeadMain3_1);
      this.wolfBody.addChild(this.wolfTail);
      this.wolfBody.addChild(this.wolfLeg2);
      this.wolfBody_1.addChild(this.wolfLeg3_1);
      this.wolfBody_1.addChild(this.wolfLeg1_1);
      this.wolfHeadMain0_2.addChild(this.wolfHeadMain3_2);
      this.wolfHeadMain0_1.addChild(this.wolfHeadMain2_1);
      this.wolfBody_1.addChild(this.wolfLeg4_1);
      this.bipedBody.addChild(this.bipedLeftArm);
      this.wolfBody_1.addChild(this.wolfHeadMain0_2);
      this.bipedRightArm.addChild(this.shaft);
      this.wolfBody.addChild(this.wolfLeg4);
      this.wolfBody_1.addChild(this.wolfLeg2_1);
      this.bipedBody.addChild(this.bipedRightArm);
      this.wolfBody.addChild(this.wolfLeg3);
      this.wolfBody_1.addChild(this.wolfMane_1);
      this.wolfBody.addChild(this.wolfMane);
      this.bipedBody.addChild(this.bipedRightLeg);
      this.wolfHeadMain0_2.addChild(this.wolfHeadMain1_2);
      this.wolfHeadMain0_2.addChild(this.wolfHeadMain2_2);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GL11.glPushMatrix();
      GL11.glTranslatef(this.bipedBody.offsetX, this.bipedBody.offsetY, this.bipedBody.offsetZ);
      GL11.glTranslatef(this.bipedBody.rotationPointX * f5, this.bipedBody.rotationPointY * f5, this.bipedBody.rotationPointZ * f5);
      GL11.glScaled(0.7D, 0.7D, 0.7D);
      GL11.glTranslatef(-this.bipedBody.offsetX, -this.bipedBody.offsetY, -this.bipedBody.offsetZ);
      GL11.glTranslatef(-this.bipedBody.rotationPointX * f5, -this.bipedBody.rotationPointY * f5, -this.bipedBody.rotationPointZ * f5);
      this.bipedBody.render(f5);
      GL11.glPopMatrix();
      this.shape37.render(f5);
      this.shape1_2.render(f5);
      this.shape1.render(f5);
      GL11.glPushMatrix();
      GL11.glTranslatef(this.wolfBody.offsetX, this.wolfBody.offsetY, this.wolfBody.offsetZ);
      GL11.glTranslatef(this.wolfBody.rotationPointX * f5, this.wolfBody.rotationPointY * f5, this.wolfBody.rotationPointZ * f5);
      GL11.glScaled(0.5D, 0.5D, 0.5D);
      GL11.glTranslatef(-this.wolfBody.offsetX, -this.wolfBody.offsetY, -this.wolfBody.offsetZ);
      GL11.glTranslatef(-this.wolfBody.rotationPointX * f5, -this.wolfBody.rotationPointY * f5, -this.wolfBody.rotationPointZ * f5);
      this.wolfBody.render(f5);
      GL11.glPopMatrix();
      this.shape1_1.render(f5);
      GL11.glPushMatrix();
      GL11.glTranslatef(this.wolfBody_1.offsetX, this.wolfBody_1.offsetY, this.wolfBody_1.offsetZ);
      GL11.glTranslatef(this.wolfBody_1.rotationPointX * f5, this.wolfBody_1.rotationPointY * f5, this.wolfBody_1.rotationPointZ * f5);
      GL11.glScaled(0.5D, 0.5D, 0.5D);
      GL11.glTranslatef(-this.wolfBody_1.offsetX, -this.wolfBody_1.offsetY, -this.wolfBody_1.offsetZ);
      GL11.glTranslatef(-this.wolfBody_1.rotationPointX * f5, -this.wolfBody_1.rotationPointY * f5, -this.wolfBody_1.rotationPointZ * f5);
      this.wolfBody_1.render(f5);
      GL11.glPopMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
