package com.emoniph.witchery.client.model;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

@SideOnly(Side.CLIENT)
public class ModelGarlicGarland extends ModelBase {

   public ModelRenderer garlicC;
   public ModelRenderer garlicA;
   public ModelRenderer garlicE;
   public ModelRenderer garlicD;
   public ModelRenderer garlicB;
   public ModelRenderer string3;
   public ModelRenderer string4;
   public ModelRenderer string1;
   public ModelRenderer string2;
   public ModelRenderer garlic1;
   public ModelRenderer garlic2;
   public ModelRenderer garlic3;
   public ModelRenderer garlic4;
   public ModelRenderer garlic1_1;
   public ModelRenderer garlic2_1;
   public ModelRenderer garlic3_1;
   public ModelRenderer garlic4_1;
   public ModelRenderer garlic1_2;
   public ModelRenderer garlic2_2;
   public ModelRenderer garlic3_2;
   public ModelRenderer garlic4_2;
   public ModelRenderer garlic1_3;
   public ModelRenderer garlic2_3;
   public ModelRenderer garlic3_3;
   public ModelRenderer garlic4_3;
   public ModelRenderer garlic1_4;
   public ModelRenderer garlic2_4;
   public ModelRenderer garlic3_4;
   public ModelRenderer garlic4_4;


   public ModelGarlicGarland() {
      super.textureWidth = 32;
      super.textureHeight = 32;
      this.garlic4 = new ModelRenderer(this, 0, 23);
      this.garlic4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic4.addBox(-2.0F, 7.0F, -2.0F, 4, 1, 4, 0.0F);
      this.garlic3 = new ModelRenderer(this, 0, 13);
      this.garlic3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic3.addBox(-3.5F, 4.0F, -3.5F, 7, 3, 7, 0.0F);
      this.garlicC = new ModelRenderer(this, 0, 0);
      this.garlicC.setRotationPoint(0.0F, 0.0F, 7.0F);
      this.garlicC.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
      this.garlic1_2 = new ModelRenderer(this, 0, 3);
      this.garlic1_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic1_2.addBox(-1.5F, 2.0F, -1.5F, 3, 1, 3, 0.0F);
      this.garlicD = new ModelRenderer(this, 0, 0);
      this.garlicD.setRotationPoint(2.5F, 1.5F, 7.0F);
      this.garlicD.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
      this.garlic3_4 = new ModelRenderer(this, 0, 13);
      this.garlic3_4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic3_4.addBox(-3.5F, 4.0F, -3.5F, 7, 3, 7, 0.0F);
      this.garlic1 = new ModelRenderer(this, 0, 3);
      this.garlic1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic1.addBox(-1.5F, 2.0F, -1.5F, 3, 1, 3, 0.0F);
      this.garlic1_3 = new ModelRenderer(this, 0, 3);
      this.garlic1_3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic1_3.addBox(-1.5F, 2.0F, -1.5F, 3, 1, 3, 0.0F);
      this.garlic4_1 = new ModelRenderer(this, 0, 23);
      this.garlic4_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic4_1.addBox(-2.0F, 7.0F, -2.0F, 4, 1, 4, 0.0F);
      this.garlic1_1 = new ModelRenderer(this, 0, 3);
      this.garlic1_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic1_1.addBox(-1.5F, 2.0F, -1.5F, 3, 1, 3, 0.0F);
      this.string2 = new ModelRenderer(this, 6, 0);
      this.string2.setRotationPoint(-3.0F, 1.8F, 7.0F);
      this.string2.addBox(0.0F, -0.5F, -0.5F, 4, 1, 1, -0.4F);
      this.setRotateAngle(this.string2, 0.0F, 0.0F, -0.5462881F);
      this.garlic3_3 = new ModelRenderer(this, 0, 13);
      this.garlic3_3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic3_3.addBox(-3.5F, 4.0F, -3.5F, 7, 3, 7, 0.0F);
      this.garlicE = new ModelRenderer(this, 0, 0);
      this.garlicE.setRotationPoint(5.0F, 0.0F, 7.0F);
      this.garlicE.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
      this.garlic1_4 = new ModelRenderer(this, 0, 3);
      this.garlic1_4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic1_4.addBox(-1.5F, 2.0F, -1.5F, 3, 1, 3, 0.0F);
      this.garlic2_4 = new ModelRenderer(this, 0, 7);
      this.garlic2_4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic2_4.addBox(-2.5F, 3.0F, -2.5F, 5, 1, 5, 0.0F);
      this.garlic2 = new ModelRenderer(this, 0, 7);
      this.garlic2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic2.addBox(-2.5F, 3.0F, -2.5F, 5, 1, 5, 0.0F);
      this.string3 = new ModelRenderer(this, 6, 0);
      this.string3.setRotationPoint(-0.4F, -0.3F, 7.0F);
      this.string3.addBox(0.0F, -0.5F, -0.5F, 4, 1, 1, -0.4F);
      this.setRotateAngle(this.string3, 0.0F, 0.0F, 0.5462881F);
      this.garlic4_3 = new ModelRenderer(this, 0, 23);
      this.garlic4_3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic4_3.addBox(-2.0F, 7.0F, -2.0F, 4, 1, 4, 0.0F);
      this.string1 = new ModelRenderer(this, 6, 0);
      this.string1.setRotationPoint(-5.4F, -0.3F, 7.0F);
      this.string1.addBox(0.0F, -0.5F, -0.5F, 4, 1, 1, -0.4F);
      this.setRotateAngle(this.string1, 0.0F, 0.0F, 0.5462881F);
      this.garlic2_1 = new ModelRenderer(this, 0, 7);
      this.garlic2_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic2_1.addBox(-2.5F, 3.0F, -2.5F, 5, 1, 5, 0.0F);
      this.string4 = new ModelRenderer(this, 6, 0);
      this.string4.setRotationPoint(2.0F, 1.8F, 7.0F);
      this.string4.addBox(0.0F, -0.5F, -0.5F, 4, 1, 1, -0.4F);
      this.setRotateAngle(this.string4, 0.0F, 0.0F, -0.5462881F);
      this.garlic3_2 = new ModelRenderer(this, 0, 13);
      this.garlic3_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic3_2.addBox(-3.5F, 4.0F, -3.5F, 7, 3, 7, 0.0F);
      this.garlicA = new ModelRenderer(this, 0, 0);
      this.garlicA.setRotationPoint(-5.0F, 0.0F, 7.0F);
      this.garlicA.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
      this.garlic4_4 = new ModelRenderer(this, 0, 23);
      this.garlic4_4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic4_4.addBox(-2.0F, 7.0F, -2.0F, 4, 1, 4, 0.0F);
      this.garlicB = new ModelRenderer(this, 0, 0);
      this.garlicB.setRotationPoint(-2.5F, 1.5F, 7.0F);
      this.garlicB.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
      this.garlic4_2 = new ModelRenderer(this, 0, 23);
      this.garlic4_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic4_2.addBox(-2.0F, 7.0F, -2.0F, 4, 1, 4, 0.0F);
      this.garlic2_3 = new ModelRenderer(this, 0, 7);
      this.garlic2_3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic2_3.addBox(-2.5F, 3.0F, -2.5F, 5, 1, 5, 0.0F);
      this.garlic2_2 = new ModelRenderer(this, 0, 7);
      this.garlic2_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic2_2.addBox(-2.5F, 3.0F, -2.5F, 5, 1, 5, 0.0F);
      this.garlic3_1 = new ModelRenderer(this, 0, 13);
      this.garlic3_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.garlic3_1.addBox(-3.5F, 4.0F, -3.5F, 7, 3, 7, 0.0F);
      this.garlicC.addChild(this.garlic4);
      this.garlicC.addChild(this.garlic3);
      this.garlicE.addChild(this.garlic1_2);
      this.garlicB.addChild(this.garlic3_4);
      this.garlicC.addChild(this.garlic1);
      this.garlicD.addChild(this.garlic1_3);
      this.garlicA.addChild(this.garlic4_1);
      this.garlicA.addChild(this.garlic1_1);
      this.garlicD.addChild(this.garlic3_3);
      this.garlicB.addChild(this.garlic1_4);
      this.garlicB.addChild(this.garlic2_4);
      this.garlicC.addChild(this.garlic2);
      this.garlicD.addChild(this.garlic4_3);
      this.garlicA.addChild(this.garlic2_1);
      this.garlicE.addChild(this.garlic3_2);
      this.garlicB.addChild(this.garlic4_4);
      this.garlicE.addChild(this.garlic4_2);
      this.garlicD.addChild(this.garlic2_3);
      this.garlicE.addChild(this.garlic2_2);
      this.garlicA.addChild(this.garlic3_1);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      double SCALE = 0.21D;
      GL11.glPushMatrix();
      GL11.glTranslatef(this.garlicC.offsetX, this.garlicC.offsetY, this.garlicC.offsetZ);
      GL11.glTranslatef(this.garlicC.rotationPointX * f5, this.garlicC.rotationPointY * f5, this.garlicC.rotationPointZ * f5);
      GL11.glScaled(0.21D, 0.21D, 0.21D);
      GL11.glTranslatef(-this.garlicC.offsetX, -this.garlicC.offsetY, -this.garlicC.offsetZ);
      GL11.glTranslatef(-this.garlicC.rotationPointX * f5, -this.garlicC.rotationPointY * f5, -this.garlicC.rotationPointZ * f5);
      this.garlicC.render(f5);
      GL11.glPopMatrix();
      GL11.glPushMatrix();
      GL11.glTranslatef(this.garlicD.offsetX, this.garlicD.offsetY, this.garlicD.offsetZ);
      GL11.glTranslatef(this.garlicD.rotationPointX * f5, this.garlicD.rotationPointY * f5, this.garlicD.rotationPointZ * f5);
      GL11.glScaled(0.21D, 0.21D, 0.21D);
      GL11.glTranslatef(-this.garlicD.offsetX, -this.garlicD.offsetY, -this.garlicD.offsetZ);
      GL11.glTranslatef(-this.garlicD.rotationPointX * f5, -this.garlicD.rotationPointY * f5, -this.garlicD.rotationPointZ * f5);
      this.garlicD.render(f5);
      GL11.glPopMatrix();
      this.string2.render(f5);
      GL11.glPushMatrix();
      GL11.glTranslatef(this.garlicE.offsetX, this.garlicE.offsetY, this.garlicE.offsetZ);
      GL11.glTranslatef(this.garlicE.rotationPointX * f5, this.garlicE.rotationPointY * f5, this.garlicE.rotationPointZ * f5);
      GL11.glScaled(0.21D, 0.21D, 0.21D);
      GL11.glTranslatef(-this.garlicE.offsetX, -this.garlicE.offsetY, -this.garlicE.offsetZ);
      GL11.glTranslatef(-this.garlicE.rotationPointX * f5, -this.garlicE.rotationPointY * f5, -this.garlicE.rotationPointZ * f5);
      this.garlicE.render(f5);
      GL11.glPopMatrix();
      this.string3.render(f5);
      this.string1.render(f5);
      this.string4.render(f5);
      GL11.glPushMatrix();
      GL11.glTranslatef(this.garlicA.offsetX, this.garlicA.offsetY, this.garlicA.offsetZ);
      GL11.glTranslatef(this.garlicA.rotationPointX * f5, this.garlicA.rotationPointY * f5, this.garlicA.rotationPointZ * f5);
      GL11.glScaled(0.21D, 0.21D, 0.21D);
      GL11.glTranslatef(-this.garlicA.offsetX, -this.garlicA.offsetY, -this.garlicA.offsetZ);
      GL11.glTranslatef(-this.garlicA.rotationPointX * f5, -this.garlicA.rotationPointY * f5, -this.garlicA.rotationPointZ * f5);
      this.garlicA.render(f5);
      GL11.glPopMatrix();
      GL11.glPushMatrix();
      GL11.glTranslatef(this.garlicB.offsetX, this.garlicB.offsetY, this.garlicB.offsetZ);
      GL11.glTranslatef(this.garlicB.rotationPointX * f5, this.garlicB.rotationPointY * f5, this.garlicB.rotationPointZ * f5);
      GL11.glScaled(0.21D, 0.21D, 0.21D);
      GL11.glTranslatef(-this.garlicB.offsetX, -this.garlicB.offsetY, -this.garlicB.offsetZ);
      GL11.glTranslatef(-this.garlicB.rotationPointX * f5, -this.garlicB.rotationPointY * f5, -this.garlicB.rotationPointZ * f5);
      this.garlicB.render(f5);
      GL11.glPopMatrix();
   }

   private void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
