package com.emoniph.witchery.worldgen;

import com.emoniph.witchery.entity.EntityGoblin;
import com.emoniph.witchery.worldgen.ComponentClonedStructure;
import java.util.Random;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.nbt.NBTTagList;
import net.minecraft.world.World;
import net.minecraft.world.gen.structure.StructureBoundingBox;

public class ComponentGoblinHut extends ComponentClonedStructure {

   public ComponentGoblinHut() {}

   public ComponentGoblinHut(int direction, Random random, int x, int z, int w, int h, int d) {
      super(direction, random, x, z, w, h, d);
   }

   protected NBTTagCompound getSchematic(World world, Random random) {
      NBTTagCompound nbtSchematic = new NBTTagCompound();
      NBTTagList nbtList = new NBTTagList();
      NBTTagCompound nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:oak_stairs");
      nbtBlock.setInteger("m", 4);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:oak_stairs");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:oak_stairs");
      nbtBlock.setInteger("m", 4);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:planks");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 7);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:oak_stairs");
      nbtBlock.setInteger("m", 5);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_door");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_door");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 5);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 6);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:planks");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:oak_stairs");
      nbtBlock.setInteger("m", 6);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 5);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:stone_slab");
      nbtBlock.setInteger("m", 3);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 9);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:stone_slab");
      nbtBlock.setInteger("m", 3);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:stone_slab");
      nbtBlock.setInteger("m", 3);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 9);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 5);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:oak_stairs");
      nbtBlock.setInteger("m", 7);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:planks");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 3);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 2);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 7);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:stone_slab");
      nbtBlock.setInteger("m", 3);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 3);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:cauldron");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:stone_slab");
      nbtBlock.setInteger("m", 3);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 2);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 6);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:planks");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 2);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:oak_stairs");
      nbtBlock.setInteger("m", 6);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:birch_stairs");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 4);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:stone_slab");
      nbtBlock.setInteger("m", 3);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 9);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:stone_slab");
      nbtBlock.setInteger("m", 3);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:stone_slab");
      nbtBlock.setInteger("m", 3);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 9);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 4);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:oak_stairs");
      nbtBlock.setInteger("m", 7);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:planks");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 9);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 7);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 9);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 4);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 8);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 9);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:torch");
      nbtBlock.setInteger("m", 5);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtBlock.setInteger("m", 6);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:planks");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:oak_stairs");
      nbtBlock.setInteger("m", 5);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:planks");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:fence");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:spruce_stairs");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:oak_stairs");
      nbtBlock.setInteger("m", 5);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:log");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:wooden_slab");
      nbtBlock.setInteger("m", 1);
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtBlock = new NBTTagCompound();
      nbtBlock.setString("n", "minecraft:air");
      nbtList.appendTag(nbtBlock);
      nbtSchematic.setTag("blocks", nbtList);
      nbtSchematic.setInteger("xMax", 7);
      nbtSchematic.setInteger("yMax", 6);
      nbtSchematic.setInteger("zMax", 7);
      return nbtSchematic;
   }

   protected void spawnInhabitant(World world, StructureBoundingBox bounds) {
      EntityGoblin goblin = new EntityGoblin(world);
      goblin.func_110163_bv();
      goblin.setLocationAndAngles((double)bounds.getCenterX(), (double)(bounds.maxY - 4), (double)bounds.getCenterZ(), 0.0F, 0.0F);
      world.spawnEntityInWorld(goblin);
   }
}
